# Generated by Django 4.1.7 on 2023-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
